
GO
SET IDENTITY_INSERT [SGBD].[instancia] ON 

INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (10, 1, 1, NULL, NULL, N'MS SQL Server', N'10.0.26.11', N'SEDE', NULL, NULL, N'S-SEBN2611,1433', 1433, 0, N'Standard Edition (64-bit)', N'14.0.2037.2', NULL, N'Servidor de dados consolidados do BI mais ETL.                                                      ', N'Equipe de BI                                                                                        ', 12288, 8, 1, CAST(N'2022-04-18T17:44:34.320' AS DateTime), 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (11, 2, 4, NULL, NULL, N'MS SQL Server', N'10.0.17.95', N'SEDE', NULL, NULL, N'S-SEBN95,1433', 1433, 0, N'Enterprise Edition (64-bit)', N'14.0.3436.1', NULL, N'Servidor de Send Box.                                                                               ', N'Equipe de BI                                                                                        ', 2147483647, 6, 1, CAST(N'2022-05-09T22:50:40.627' AS DateTime), 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (12, 3, 1, NULL, NULL, N'MS SQL Server', N'10.0.17.26', N'SEDE', NULL, NULL, N'S-SEBN26,1433', 1433, 0, N'Enterprise Edition (64-bit)', N'14.0.3436.1', NULL, N'Servidor do Power BI Report Srever Conexão.                                                         ', N'Equipe de BI                                                                                        ', 8192, 4, 1, CAST(N'2022-04-26T19:33:33.940' AS DateTime), 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (13, 4, 1, NULL, NULL, N'MS SQL Server', N'10.0.17.94', N'SEDE', NULL, NULL, N'S-SEBN94,1433', 1433, 0, N'Enterprise Edition (64-bit)', N'14.0.3436.1', NULL, N'Servidor do Power BI Report Srever Dados                                                            ', N'Equipe de BI                                                                                        ', 12228, 8, 1, CAST(N'2022-04-19T12:07:05.343' AS DateTime), 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (14, 5, 1, NULL, NULL, N'MS SQL Server', N'10.0.4.110', N'SEDE', NULL, NULL, N'S-SEBN27110,1433', 1433, 0, NULL, NULL, NULL, N'Servidor de Analise Server DW.                                                                      ', N'Equipe de BI                                                                                        ', NULL, NULL, 1, NULL, 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (15, 6, 1, NULL, NULL, N'MS SQL Server', N'10.0.4.110', N'SEDE', NULL, NULL, N'S-SEBN27160,1433', 1433, 0, NULL, NULL, NULL, N'Servidor de Analise Server DW.                                                                      ', N'Equipe de BI                                                                                        ', NULL, NULL, 1, NULL, 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (16, 7, 1, NULL, NULL, N'MS SQL Server', N'10.0.26.36', N'SEDE', NULL, NULL, N'S-SEBN2631,1433', 1433, 0, N'Enterprise Edition (64-bit)', N'10.50.6560.0', NULL, N'Servidor de banco do Sharepoint 2010                                                                ', N'Equipe de BI                                                                                        ', 2147483647, 4, 1, CAST(N'2021-10-22T14:45:20.907' AS DateTime), 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (17, 11, 1, NULL, NULL, N'MS SQL Server', N'10.0.26.189', N'SEDE', NULL, NULL, N'S-SEBN26189,1433', 1433, 0, N'Standard Edition (64-bit)', N'15.0.4138.2', NULL, N'Servidor de banco do SCCM.                                                                          ', N'Equipe de Infra                                                                                     ', 20384, 8, 1, CAST(N'2021-07-14T20:19:45.457' AS DateTime), 1)
INSERT [SGBD].[instancia] ([idInstancia], [idSHServidor], [IdTrilha], [idcluster], [Instancia], [SGBD], [IP], [Regiao], [dependencia], [AdSite], [conectstring], [Porta], [Cluster], [Versao], [ProductVersion], [Descricao], [FuncaoServer], [SobreAdministracao], [MemoryConfig], [CPU], [EstanciaAtivo], [StartInstancia], [Ativo]) VALUES (18, 8, 1, 1, NULL, N'MS SQL Server', N'10.0.17.229', N'SEDE', NULL, NULL, N'S-SEBN229,1433', 1433, 1, N'Enterprise Edition (64-bit)', N'11.0.6248.0', NULL, N'Servidor de banco do Sharepoint 2013                                                                ', N'Equipe de BI                                                                                        ', 20480, 8, 1, CAST(N'2021-10-01T17:50:08.737' AS DateTime), 1)
SET IDENTITY_INSERT [SGBD].[instancia] OFF
