Write-Output "Welcome to Nutanix PowerShell Commands"
Write-Output "                    "
Write-Output ".,,,,,,,.            ,#########."
Write-Output "  .,,,,,,,.        ,########."
Write-Output "    .,,,,,,,.    ,#######."
Write-Output "      .,,,,,,,.  ,#####."
Write-Output "        .,,,,,,,. ,##."
Write-Output "          .,,,,,,."
Write-Output "        .,,,,,,,. ,#."
Write-Output "      .,,,,,,,.  ,#####."
Write-Output "    .,,,,,,,.    ,#######."
Write-Output "  .,,,,,,,.        ,########."
Write-Output ".,,,,,,,.            ,#########."